did one or two
JerryJeager/COS-431-DSA- pull request #1
Opened 2024-06-09 17:32 UTC by c0deMercenary

2024-06-09 18:05 UTC, JerryJeager reviewed
LGTM

2024-06-09 18:07 UTC, JerryJeager requested changes

2024-06-09 18:07 UTC, JerryJeager commented on Search.class
I don't think we need the binary file, can you remove this and add a .gitignore for all .class files? Thanks

2024-06-09 18:27 UTC, c0deMercenary commented
Aigt

On Sun, 9 Jun 2024, 19:07 Amadi Jerry, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On Search.class
> <https://github.com/JerryJeager/COS-431-DSA-/pull/1#discussion_r1632362333>
> :
>
> I don't think we need the binary file, can you remove this and add a
> .gitignore for all .class files? Thanks
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JerryJeager/COS-431-DSA-/pull/1#pullrequestreview-2106325343>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXHM2LTJ4NLRIGJSWNCMVPTZGSKV5AVCNFSM6AAAAABJBBZIUGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCMBWGMZDKMZUGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-06-09 18:34 UTC, c0deMercenary commented on Search.class
resolved

2024-06-11 05:19 UTC, JerryJeager approved these changes

2024-06-11 05:20 UTC, merged